i                    		=> Mode insertion
echap				=> sortir d'un mode
:q				=> quitter
:q!				=> forcer a quitter sans enregistrer
:w				=> enregistrer
:wq				=> enregistrer et quitter
G  				=> Déplacer en haut du fichier
GG 				=> Déplacer en bas du fichier
$                               => Fin de ligne
0                               => Début de ligne
w                               => Sauter des mots
yy				=> copier la ligne
:e nouveauFichier 		=> Créé un nouveau fichier
:ls 				=> Liste des buffers ouverts
ctrl + w v			=> Split vertical
ctrl + w h			=> Split horizontal
ctrl + w flèche			=> Se déplacer dans les splits
ctrl + fleche droite		=> avancer d'un mot
ctrl + fleche gauche		=> reculer d'un mot
x				=> Effacer un caractère
dd				=> Couper la ligne
dw				=> effacer le texte jusqu'a la fin du mot
d$				=> Supprimer du curseur à la fin de la ligne
d0				=> Supprimer du curseur au debut de la ligne
y				=> Copier
p				=> Coller
:r				=> coller le contenu du fichier dans le fichier courant
>>				=> Indenter à droite
<<				=> Indenter à gauche
u				=> Annuler la dernière opération effectuée
U				=> Remettre en place la ligne
/texte				=> rechercher du texte 'texte'
%s/toto/tonton/g		=> Remplacer 'toto' par 'tonton' dans tout le fichier
:!commande			=> Executer une commande externe à VIM
R				=> Remplacer chaque caractère a la suite

